version: "3.8"
services:
  client:
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
      - ./client/nginx-ssl.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
